---
title: "Refugee Resettlements in the USA"
author: "Ji In Choi (jic2124), Jung Ah Shin (js5569), Olivia Wang (yw3324), Tiffany Zhu (tz2196)"
date: "December 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
```

## Introduction

## Data Sources

## Data Transformation
```{r}
# Used to clean the Arrivals data
clean_arrival <- function(file, sheet_name) {
  dat <- read_excel(file, sheet = sheet_name)
  dat1 <- subset(dat, select = c(...6, ...8,...9))
  dat2 <-subset(dat, select = c(...15,...18,...19)) 
  dat3 <-subset(dat, select = c(...23,...25,...27))

  dat1<-dat1 %>% drop_na()
  dat2<-dat2 %>% drop_na()
  dat3<-dat3 %>% drop_na()

  # set first row (State, Cases, Inds) as column name
  colnames(dat1) <- as.character(unlist(dat1[1,]))
  dat1 = dat1[-1, ]
  colnames(dat2) <- as.character(unlist(dat2[1,]))
  dat2 = dat2[-1, ]
  colnames(dat3) <- as.character(unlist(dat3[1,]))
  dat3 = dat3[-1, ]

  # Grouping columns together
  combined <- rbind(dat1,dat2)
  combined <- rbind(combined,dat3)

  # State,Cases,Inds

  combined$Cases <-as.numeric(as.character(combined$Cases))
  combined$Inds <-as.numeric(as.character(combined$Inds))
  
  return (combined)
}


```

```{r}
# Used to clean the Demographics data
clean_demographics <- function(file, sheet_name) {
  df <- read_excel(file, sheet = sheet_name)
  
  if (sheet_name == 'Age Group') {
    column_names = c('Department of State','...2', '...3', '...4')
  }
  else if (sheet_name == 'Religion') {
    column_names = c('Department of State','...2', '...4', '...6')
  }
  else if (sheet_name == 'Ethnicity' | sheet_name == 'Education' | sheet_name == 'Native Language') {
    column_names = c('Department of State','...2', '...3', '...5')
  }
  
  df2 <- subset(df, select = column_names)
  df3 <- df2[complete.cases(df2), ]
  df4 = df3[-nrow(df3), ]
  
  #print(file)
  #file_replaced <- gsub(pattern="demographics/", replacement=".", file, fixed = TRUE)
  
  # file_unpacked <- unlist(strsplit(file_replaced, split='.', fixed=TRUE))
  file_unpacked <- unlist(strsplit(file, 'demographics/'))
  file_unpacked2 <- unlist(strsplit(file_unpacked[2], '_Demographics'))
  country_name = file_unpacked2[1]

  colnames(df4) = c(sheet_name, 'Male', 'Female', 'Total')
  
  df4$country <- rep(country_name, nrow(df4))
  
  return(df4)
}

```

```{r}
# Cleans and combines all the files in the directory given by path
combine_files <- function(path, data_cleaner, sheet_name, title) {
  df = data.frame()
  files <- list.files(path=path, pattern="*.xlsx", full.names=TRUE, recursive=FALSE)
  for (file in files){
    cleaned_data = data_cleaner(file, sheet_name)
    year_extract <- unlist(strsplit(file, title))
    cleaned_data$Year <- as.numeric(gsub(".xlsx", "", year_extract[2]))
    df <- rbind(df, cleaned_data)}
  return (df)
}
#Examples

# path = "~/Desktop/Projects/EDAV/edav-final-project-41/data/raw/demographics"
# title = 'Demographics_'
# function
# sheet_name = 'Ethnicity'
# sheet_name = 'Age Group'
# sheet_name = 'Religion'
# sheet_name = 'Education'
# sheet_name = 'Native Language'
# data_cleaner = clean_demographics

# path = "~/Desktop/Projects/EDAV/edav-final-project-41/data/raw/all_arrivals"
# title = 'Arrivals_'
# sheet_name = 'Detailed'
# data_cleaner = clean_arrival

# df_test3 <- combine_files(path, clean_demographics, sheet_name, title)
```

```{r}
# Cleaned all_arrivals data converted to csv files
save_cleaned_all_arrivals <- function() {
    path = "~/Desktop/CU/F19/STATW5702_EDAV/edav-final-project-41/data/raw/all_arrivals"
  title = 'Arrivals_'
  sheet_name = 'Detailed'
  data_cleaner = clean_arrival
  arrival_df <- combine_files(path, data_cleaner, sheet_name, title)
  write.csv(arrival_df, file = "~/Desktop/CU/F19/STATW5702_EDAV/edav-final-project-41/data/clean/all_arrivals.csv", row.names = FALSE)
}

# Cleaned demographics data converted to csv files
save_cleaned_all_demographics <- function() {
  path = "~/Desktop/CU/F19/STATW5702_EDAV/edav-final-project-41/data/raw/demographics"
  title = 'Demographics_'
  sheet_names = c('Ethnicity', 'Age Group', 'Religion', 'Education', 'Native Language')
  file_names = c('ethnicity', 'age_group', 'religion', 'education', 'native_language')
  data_cleaner = clean_demographics
  
  for (i in 1:length(sheet_names)) {
    demographic_df <- combine_files(path, data_cleaner, sheet_names[i], title)
    file_name = paste("~/Desktop/CU/F19/STATW5702_EDAV/edav-final-project-41/data/clean/", file_names[i], sep='')
    write.csv(demographic_df, file = paste(file_name, '.csv', sep=''), row.names = FALSE)
  }
}
```


## Missing Values

## Results
```{r}
# Read cleaned data from github
arrival_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/all_arrivals.csv')
age_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/age_group.csv')
ethnicity_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/ethnicity.csv')
religion_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/religion.csv')
education_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/education.csv')
native_language_df = read.csv('https://raw.githubusercontent.com/tlzhu19/edav-final-project-41/master/data/clean/native_language.csv')
```


## Interactive Component

## Conclusion
